export const getSearchValue = (state) => state.filters.search;
export const getFromDateValue = (state) => state.filters.fromDate;
export const getToDateValue = (state) => state.filters.toDate;
export const getStatusValues = (state) => state.filters.status;
export const getFromSumValue = (state) => state.filters.fromSum;
export const getToSumValue = (state) => state.filters.toSum;
export const getSortCell = (state) => state.filters.sortCell;
export const getSortDirection = (state) => state.filters.isSortAscending;
export const getPage = (state) => state.filters.page;
